#!/usr/bin/env python3
"""Per-binary link sets for the test tree, computed by fmake.

`tests/Makefile` used to build one `libhydra_app.a` and link every binary
against it. That is against a written rule in `build-and-commit.md` and it
cost what the rule says it costs: the archive is rebuilt when any of its
inputs changes and all seventy binaries then relink, measured at a flat 19s
whether the change reached three files or eight.

The archive was standing in for a computation -- which objects does this
binary actually need -- and fmake performs exactly that computation: compile,
read the symbol tables with `nm`, and close transitively over undefined
symbols. That is the same thing the linker does when deciding which members
to pull from an archive, so the answer is exact rather than a guess from the
include graph.

So: ask fmake once, rewrite its answer into the object names `tests/Makefile`
uses, and write `tests/objsets.mk`. No archive, and each binary relinks only
when something it genuinely contains has changed.

**The generated file carries the source list it was generated from**, and
`tests/Makefile` refuses to build when that no longer matches the tree. A
generated file which silently describes a tree that has moved on is the exact
failure this project keeps finding, and a stale link set fails as an undefined
symbol a long way from the file somebody added.
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# fmake writes `$(FM_BUILD_DIR)/<path>.cpp.o`; tests/Makefile has three object
# namespaces and they are not the same shape.
RE_APP  = re.compile(r"^\$\(FM_BUILD_DIR\)/src/(.+)\.cpp\.o$")
RE_MOC  = re.compile(r"^\$\(FM_BUILD_DIR\)/moc/src/moc_(.+)\.cpp\.o$")
RE_TMOC = re.compile(r"^\$\(FM_BUILD_DIR\)/moc/tests/moc_(.+)\.cpp\.o$")
RE_SELF = re.compile(r"^\$\(FM_BUILD_DIR\)/tests/(?:live/)?(.+)\.cpp\.o$")


def translate(obj, program):
	"""One fmake object path in tests/Makefile's naming, or None to drop it."""
	m = RE_APP.match(obj)
	if m:
		return "$(BUILD_DIR)/app/%s.o" % m.group(1)
	m = RE_MOC.match(obj)
	if m:
		return "$(BUILD_DIR)/moc/moc_%s.o" % m.group(1)
	m = RE_TMOC.match(obj)
	if m:
		return "$(BUILD_DIR)/tmoc/moc_%s.o" % m.group(1)
	m = RE_SELF.match(obj)
	if m:
		# The program's own object is already the first prerequisite of the
		# link rule, so listing it again would put it on the command line
		# twice. Harmless to the linker, confusing to read.
		return None if m.group(1) == program else "$(BUILD_DIR)/%s.o" % m.group(1)
	return None


def sources():
	"""Every source the test tree builds a program from, as the guard sees it."""
	out = []
	for d, pattern in (("tests", "test_"), ("tests/live", "try_")):
		full = os.path.join(ROOT, d)
		for name in sorted(os.listdir(full)):
			if name.startswith(pattern) and name.endswith(".cpp"):
				out.append("%s/%s" % (d, name))
	return out


def main():
	fragment = subprocess.run(["fmake", "--eject", "make-fragment"],
	                           cwd=ROOT, capture_output=True, text=True)
	if fragment.returncode != 0:
		sys.stderr.write(fragment.stderr[-2000:])
		return "fmake --eject failed"

	# FM_<NAME>_OBJS = \<tab>obj \ ... -- one block per program.
	blocks = re.findall(r"^FM_([A-Z0-9_]+)_OBJS = \\\n((?:\t.*\\?\n)+)",
	                     fragment.stdout, re.M)
	sets = {}
	for name, body in blocks:
		program = name.lower()
		objs = [o.strip().rstrip("\\").strip() for o in body.split("\n")]
		translated = [translate(o, program) for o in objs if o]
		sets[program] = [t for t in translated if t]

	wanted = [os.path.basename(s)[:-4] for s in sources()]
	missing = [w for w in wanted if w not in sets]
	if missing:
		return ("fmake produced no link set for: %s" % " ".join(missing[:5]))

	lines = [
		"# Generated by tools/objsets.py -- do not edit.",
		"#",
		"# Per-binary link sets, closed over symbols by fmake. Regenerate with",
		"#",
		"#     make -C tests objsets",
		"#",
		"# The list below is the tree this was generated from. tests/Makefile",
		"# compares it against the tree it finds and refuses to build when they",
		"# differ, because a link set describing a tree that has moved on fails",
		"# as an undefined symbol a long way from the file somebody added.",
		"",
		"OBJSETS_SOURCES = \\",
	]
	src = sources()
	for i, s in enumerate(src):
		lines.append("\t%s%s" % (s, " \\" if i + 1 < len(src) else ""))
	lines.append("")
	for program in sorted(sets):
		if program not in wanted:
			continue
		objs = sets[program]
		lines.append("OBJS_%s = \\" % program)
		for i, o in enumerate(objs):
			lines.append("\t%s%s" % (o, " \\" if i + 1 < len(objs) else ""))
		if not objs:
			lines[-1] = "OBJS_%s =" % program
		lines.append("")

	path = os.path.join(ROOT, "tests", "objsets.mk")
	with open(path, "w") as fh:
		fh.write("\n".join(lines) + "\n")

	total = sum(len(v) for k, v in sets.items() if k in wanted)
	print("objsets.mk: %d programs, %d objects, %.1f each on average"
	      % (len(wanted), total, total / max(1, len(wanted))))
	return None


if __name__ == "__main__":
	sys.exit(main() or 0)
