// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <QHash>
#include <QList>
#include <QMap>
#include <QString>
#include <QUrl>

// One request the page made, and the whole of what a proposal gets to reason
// about. Deliberately thin: URLs, kinds and order, with no bodies, no cookies
// and no credentials — the §9.3 rule that a payload carries the least that can
// work applies to extraction as much as to the tree.
struct evidence_request {
	QUrl    url;
	QString kind;    // "script", "image", "other", as the interceptor saw it
	int     order = 0;
};

// What running an extractor produced.
struct extraction {
	bool    ok = false;
	QUrl    url;
	QString kind;    // "hls" | "dash" | "direct"
	QMap<QString, QString> headers;
	QString error;
};

// Whether a proposal may be offered to the user at all.
struct extractor_verdict {
	bool       usable = false;
	bool       invented = false;   // returned a URL that was never observed
	bool       is_segment = false; // returned one of a flood of near-identical
	                               // requests, which is a segment, not a stream
	bool       is_page = false;    // returned the page's own address, which is
	                               // the document asked about, not a stream in it
	bool       is_asset = false;   // the browser fetched it as an image or a
	                               // script, so it is page furniture, not video
	bool       timed_out = false;
	QString    message;
	extraction result;
};

// Site extractors: parser scripts, produced and judged as data (architecture
// doc §11.5).
//
// URL-shaped detection fails on real sites, and the knowledge that would fix
// it — which request is the manifest, how the address is assembled — changes
// every few weeks. Encoding that in C++ means a rebuild and a release per site.
// So an extractor is a script, generated by the AI path, reviewed, and stored
// like the filter list.
//
// **The safety rule is the same one §9.4 uses on the tree.** A reorganization
// that invents a tab id is rejected outright because there is no safe repair;
// an extractor that returns a URL nobody observed is rejected for the same
// reason. The model is choosing among things the page actually fetched, not
// authoring an address — and a proposal that fabricates one would send the
// user somewhere of its own devising.
//
// Scripts run in a QJSEngine: no DOM, no network, no file access, nothing of
// the host's. A script that never returns is interrupted, because a proposal
// that loops forever must not be able to hang the browser.
namespace site_extractor {

// The contract a script implements:
//
//     function extract(page, requests) {
//         // page:     { url, host }
//         // requests: [ { url, kind, order }, … ]
//         return { url: "…", kind: "hls", headers: { … } };   // or null
//     }
extraction run(const QString &source, const QUrl &page,
                const QList<evidence_request> &evidence, int timeout_ms = 2000);

// Runs it and then judges it. Nothing reaches the user without passing here.
extractor_verdict check(const QString &source, const QUrl &page,
                         const QList<evidence_request> &evidence);

}  // namespace site_extractor

// The per-site store: which script applies to which host, loaded and saved as
// plain JSON so it can be read, diffed and shared like any other rule set.
class extractor_store {
public:
	void    set_for(const QString &host, const QString &source, const QString &note);
	QString source_for(const QString &host) const;
	QString note_for(const QString &host) const;
	bool    has(const QString &host) const;
	void    remove(const QString &host);
	QStringList hosts() const;

	bool load(const QString &path);
	bool save(const QString &path) const;

private:
	struct entry { QString source; QString note; };
	QHash<QString, entry> m_by_host;
};
