// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <QHash>
#include <QList>
#include <QMap>
#include <QSet>
#include <QString>
#include <QUrl>

class helper_host;

// One request the page made, and the whole of what a proposal gets to reason
// about. Deliberately thin: URLs, kinds and order, with no bodies, no cookies
// and no credentials -- the sec 9.3 rule that a payload carries the least that can
// work applies to extraction as much as to the tree.
struct evidence_request {
	QUrl    url;
	QString kind;    // "script", "image", "other", as the interceptor saw it
	int     order = 0;
};

// What running an extractor produced.
struct extraction {
	bool    ok = false;
	QUrl    url;
	QString kind;    // "hls" | "dash" | "direct"
	QMap<QString, QString> headers;
	QString error;
};

// Whether a proposal may be offered to the user at all.
struct extractor_verdict {
	bool       usable = false;
	bool       invented = false;   // returned a URL that was never observed
	bool       is_segment = false; // returned one of a flood of near-identical
	                               // requests, which is a segment, not a stream
	bool       is_page = false;    // returned the page's own address, which is
	                               // the document asked about, not a stream in it
	bool       is_asset = false;   // the browser fetched it as an image or a
	                               // script, so it is page furniture, not video
	bool       is_piece = false;   // a manifest was confirmed beside it, so this
	                               // is one of the parts that manifest describes
	bool       timed_out = false;
	bool       helper_breach = false;  // it reached past what it was allowed, or
	                                   // spent a budget; sec 11.5.1
	bool       hardcoded = false;  // it embeds a token from this capture, so it
	                               // answers for this visit and no other
	bool       reads_note = false; // it reads the `serves` column at run time,
	                               // where that column does not exist
	QString    message;
	extraction result;
};

// Site extractors: parser scripts, produced and judged as data (architecture
// doc sec 11.5).
//
// URL-shaped detection fails on real sites, and the knowledge that would fix
// it -- which request is the manifest, how the address is assembled -- changes
// every few weeks. Encoding that in C++ means a rebuild and a release per site.
// So an extractor is a script, generated by the AI path, reviewed, and stored
// like the filter list.
//
// **The safety rule is the same one sec 9.4 uses on the tree.** A reorganization
// that invents a tab id is rejected outright because there is no safe repair;
// an extractor that returns a URL nobody observed is rejected for the same
// reason. The model is choosing among things the page actually fetched, not
// authoring an address -- and a proposal that fabricates one would send the
// user somewhere of its own devising.
//
// Scripts run in a QJSEngine: no DOM, no network, no file access, nothing of
// the host's. A script that never returns is interrupted, because a proposal
// that loops forever must not be able to hang the browser.
namespace site_extractor {

// The contract a script implements:
//
//     function extract(page, requests) {
//         // page:     { url, host }
//         // requests: [ { url, kind, order }, ... ]
//         return { url: "...", kind: "hls", headers: { ... } };   // or null
//     }
//
// `helpers` is the sec 11.5.1 tier: null for the pure tier, which is the default
// and gets no `hydra` object at all, so a script written against it cannot even
// see that the tier exists.
// Two requests are "the same shape" when they differ only in the parts that
// vary between sightings of the same thing. Shared, because the evidence fold,
// the probe ranking and the gate's segment rule must agree about it -- they were
// three consumers of two separate copies, which is a disagreement waiting to
// happen.
//
// Both parts are load-bearing, and both were learned from real evidence rather
// than guessed. Digit *runs* of two or more were collapsed originally, so a
// real flood of `seg-1`, `seg-2`, `seg-3` stayed eleven distinct shapes and
// folded into nothing. And query values rotate per request -- `kx=1785501512`
// is a timestamp and `k=` a token -- so keeping them meant the same segment
// fetched twice never matched itself. Keys are kept and values dropped: what
// makes two requests the same shape is the shape of the question, not the
// answer's credentials.
QString shape_of(const QUrl &u);

extraction run(const QString &source, const QUrl &page,
	              const QList<evidence_request> &evidence, int timeout_ms = 2000,
	              helper_host *helpers = nullptr);

// Runs it and then judges it. Nothing reaches the user without passing here.
//
// `manifests` is what the sec 10 content-type tier established, as normalised
// urls: the addresses it fetched and found to be an HLS or DASH playlist. It is
// optional in the strict sense -- the tier is allowed to be absent, blocked or
// refused, and when the set is empty this rule cannot fire and nothing changes.
// A *positive* identification is the only thing it is ever used for, so a tier
// that could not answer never costs a proposal its accept.
extractor_verdict check(const QString &source, const QUrl &page,
	                       const QList<evidence_request> &evidence,
	                       helper_host *helpers = nullptr,
	                       const QSet<QString> *manifests = nullptr);

}  // namespace site_extractor

// The per-site store: which script applies to which host, loaded and saved as
// plain JSON so it can be read, diffed and shared like any other rule set.
class extractor_store {
public:
	void    set_for(const QString &host, const QString &source, const QString &note);
	QString source_for(const QString &host) const;
	QString note_for(const QString &host) const;
	bool    has(const QString &host) const;
	void    remove(const QString &host);
	QStringList hosts() const;

	bool load(const QString &path);
	bool save(const QString &path) const;

private:
	struct entry { QString source; QString note; };
	QHash<QString, entry> m_by_host;
};
